### ISSUE TITLE
Issue with extensions and next.js@latest

### ISSUE THREAD

**Issue by DanHarman** [saitonakamura/next-awesome-typescript#3]
Hi,

I upgraded to the latest version of next and now get 404s on my tsx pages. I think there may have been a change to how extensions are configured in next. If you look at recent commits on `next-typescript` they seem to be related.

https://github.com/zeit/next-plugins/blob/master/packages/next-typescript/index.js

https://github.com/zeit/next-plugins/commit/e3080bc4fc884c92ceac4bd3aff5d72a20b42ea4#diff-396ed30462426052ff3807312843294c

https://github.com/zeit/next-plugins/commit/34cf092dba68edff3f21a324ef1c7f4c713fb44d#diff-396ed30462426052ff3807312843294c

**Comment by saitonakamura** [comment]
Thanks for the issue, I'll take a look

**Comment by saitonakamura** [comment]
@DanHarman I've fixed and published it. Can you confirm it's working fine with your project?

**Comment by DanHarman** [comment]
@saitonakamura Hey, I've tested it and all is ok. Great job and thanks for turning it around so quickly. So much nicer to come back to awesome's fast compile time vs ts-loader with next-typescript.
